コードレビュー用
shu-yamanoi/to_do pull request #1
Opened 2020-05-12 09:29 UTC by 92thunder

2020-05-12 10:03 UTC, 92thunder reviewed
永続化は次の変更でぜひ機能追加してほしい！
CSSのクラス名など微妙に書き方で悩むことあったらslackで相談してください！

2020-05-12 10:03 UTC, 92thunder commented on src/store/index.ts
> +    changeStatus(state, todo) {
changeStatusをupdateTodoから分岐したのはUIの都合ですか？
関数の仕事がはっきりするのでそれぞれ別にあってもいいと思いました

2020-05-12 10:03 UTC, 92thunder commented on src/store/index.ts
> +      for(let i = 0; i < state.todos.length; i++) {
Array.findを使うほうが最近のTS/JSらしいコードになります。find以外もぜひ調べてみてください
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2020-05-12 10:03 UTC, 92thunder commented on src/store/index.ts
> +          state.todos.splice(i, 1, state.todos[i])
↑の文で直接書き換えているのでここの処理は不要です

2020-05-12 10:03 UTC, 92thunder commented on src/store/index.ts
> +      commit('addTodo', newTodo)
IndexedDBやlocalStorageを使うと永続化してアプリっぽくなるのでぜひ機能追加してほしい

2020-05-12 10:03 UTC, 92thunder commented on src/store/index.ts
> +  modules: {
不要な行は混乱のもとになるので消すことをおすすめします

2020-05-12 10:03 UTC, 92thunder commented on src/components/TodoList.vue
> +  .todoHeader {
cssのクラス名は-つなぎのkebab-caseで書くことが一般的ですね

2020-05-12 10:03 UTC, 92thunder commented on src/components/EditTitleForm.vue
> +<style>
`<style scoped>` とすることで他のコンポーネントにCSSが影響しなくなるので基本的にscopedをつけるようにしてください

2020-05-12 10:03 UTC, 92thunder commented on src/components/SelectBox.vue
> +  import { Component, Vue, Prop } from 'vue-property-decorator';
細かいですがインデントのずれが気になります…

2020-05-12 10:03 UTC, 92thunder commented on src/components/TodoList.vue
> +      status: status,
プロパティ名と変数名が同じ場合はプロパティ名を省略して書くことができます
https://qiita.com/kura07/items/356bd37733f457d3177f#var-obj---prop-

2020-05-12 10:03 UTC, 92thunder commented on src/components/TodoList.vue
> +  deleteTodoHandle(status: 'TODO' | 'DOING' | 'DONE', id: number) {
引数で直接todoItemを受け取ってシンプルに書きましょう

2020-05-12 10:03 UTC, 92thunder commented on src/components/TodoList.vue
> +    switch (this.status) {
switchを消して1行にまとめると処理が１か所にまとまってよさそうですね
`return this.$store.state.todos.filter((todo: Todo) => todo.status === this.status)`

2020-05-12 10:03 UTC, 92thunder commented on src/store/index.ts
> +      state.todos.splice(0)
この行って意味あります？

2020-05-12 10:03 UTC, 92thunder commented on src/store/index.ts
> +      const newTodos: Todo[] = state.todos.filter(_todo => _todo.id !== todo.id)
Array.findIndexしてからそのindexを使ってArray.spliceで消すと最近のJS/TSらしいと思います

2020-06-03 08:17 UTC, 92thunder commented on .gitignore
> +docs/
@shu-yamanoi docs/が既に入ってしまっているのでgit rmでまとめて削除してくださいー

2020-06-03 08:27 UTC, 92thunder reviewed
@shu-yamanoi 確認遅れましたが追加部分にコメントしました！

2020-06-03 08:27 UTC, 92thunder commented on .gitignore
> +dist/
distは不要になったかも？

2020-06-03 08:27 UTC, 92thunder commented on src/store/index.ts
> +        const allState = JSON.parse(localStorage.getItem('allState') as string)
データを何度も取得しなくて済むよう、取得したデータを変数に入れておきましょう

2020-06-03 08:27 UTC, 92thunder commented on src/store/index.ts
> +      if(localStorage.getItem('allState')) {
localStorageのキーはデータの名前をつけましょう。todoなど
VuexのstateというのはUIの状態という意味から来てるので不自然な感じ伝わりますかね？

またキーの名前をconst TODOS_KEYなど変数にしておきましょう
打ち間違え、コピペミスのバグが発生しにくくなります

2020-06-03 08:27 UTC, 92thunder commented on src/store/index.ts
> +      let idState = Number(localStorage.getItem('idState'))
こっちも適切な名前をつけてあげましょう

2020-06-03 14:40 UTC, shu-yamanoi requested changes
@92thunder レビューありがとうございます！

2020-06-03 14:40 UTC, shu-yamanoi commented on .gitignore
> +docs/
docsは他のリポジトリで管理してみます。

2020-06-03 14:40 UTC, shu-yamanoi commented on src/store/index.ts
> +    changeStatus(state, todo) {
構造的にstatusが分離されてるわけではないのですが、一応、UIでstatusで区切られているので、なんとなく分けてみました。

2020-06-03 14:40 UTC, shu-yamanoi commented on src/store/index.ts
> +      if(localStorage.getItem('allState')) {
なるほど。たしかにかなり不自然ですね、、。

2020-06-03 14:41 UTC, shu-yamanoi approved these changes

2020-06-05 10:28 UTC, 92thunder reviewed
@shu-yamanoi 後これだけなおしたらマージしよう！

2020-06-05 10:28 UTC, 92thunder commented on src/store/index.ts
> +const allTodo = JSON.parse(localStorage.getItem(TODO_KEY) as string)
setTodo内でしか使わないのでsetTodo内の変数にするほうがいいと思う
後でコード編集するときにallTodoが最新のデータだと思い込んでいたら、他のタブでデータが変わってるのに気づかずバグに繋がるということがありそう

2020-06-06 04:31 UTC, shu-yamanoi commented on src/store/index.ts
> +const allTodo = JSON.parse(localStorage.getItem(TODO_KEY) as string)
確かにですね。

2020-06-06 12:58 UTC, 92thunder commented on package.json
> +    "deploy": "gh-pages -d dist"
デフォルトでgh-pagesブランチにpushしてくれるのね

2020-06-06 12:59 UTC, 92thunder commented
@shu-yamanoi 
LGTM！
お好きなタイミングでマージしてmasterブランチに取り込んでください！

2020-06-07 23:36 UTC, shu-yamanoi commented on package.json
> +    "deploy": "gh-pages -d dist"
gh-pagesというパッケージ使いました。

2022-07-14 00:52 UTC, closed without merging